[build]
publish = "dist"
command = "npx vite build"

[build.environment]
VITE_SUPABASE_URL = "https://zxttalysbycssowlhynq.supabase.co"
VITE_SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inp4dHRhbHlzYnljc3Nvd2xoeW5xIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODM2MTA1ODcsImV4cCI6MjA5OTE4NjU4N30.cJnMXi_UYoyYoADd-BO_hTd_rZxf6WWiYAbFOB4Upm4"

[[redirects]]
from = "/*"
to = "/index.html"
status = 200