import React, { useEffect, useState } from 'react';
import { Image as ImageIcon, X } from 'lucide-react';
import type { Material } from '../pages/DesignerQuoteGenerator';
import type { QuoteItem } from '../pages/DesignerQuoteGenerator';

type DrawerItem = QuoteItem;
interface QuoteItemDrawerProps { isOpen: boolean; item: DrawerItem | null; materials: Material[]; roomName: string; formatCurrency: (amount: number) => string; onClose: () => void; onSave: (item: DrawerItem) => void; onUpload: (file: File) => Promise<string>; }
const baseItem = (section: string): QuoteItem => ({ item_type: 'material', name: '', description: '', number_of_units: 1, quantity: 1, unit: 'sq.ft', unit_price: 0, discount_percent: 0, amount: 0, section: section as QuoteItem['section'], width_unit: 'feet', height_unit: 'feet', depth_unit: 'feet' });
const QuoteItemDrawer = ({ isOpen, item, materials, roomName, formatCurrency, onClose, onSave, onUpload }: QuoteItemDrawerProps) => {
  const [draft, setDraft] = useState<DrawerItem>(item ?? baseItem(roomName));
  const [uploading, setUploading] = useState(false);
  useEffect(() => { if (isOpen) setDraft(item ?? baseItem(roomName)); }, [isOpen, item, roomName]);
  if (!isOpen) return null;
  const update = <K extends keyof DrawerItem>(field: K, value: DrawerItem[K]) => setDraft(previous => ({ ...previous, [field]: value }));
  const isModular = draft.section === 'modular';
  const amount = isModular ? ((draft.width || 0) * (draft.height || 0) * (draft.number_of_units || 1) * (draft.per_sqft_rate || draft.unit_price || 0) * (1 - (draft.discount_percent || 0) / 100)) : ((draft.number_of_units || 1) * (draft.quantity || 0) * (draft.unit_price || 0) * (1 - (draft.discount_percent || 0) / 100));
  const selectMaterial = (id: string) => { const material = materials.find(entry => entry.id === id); if (!material) return; const price = material.is_discounted && material.discount_price !== null ? material.discount_price : material.base_price; setDraft(previous => ({ ...previous, material_id: material.id, name: material.name, description: material.description || '', unit: material.unit, unit_price: price, amount: (previous.number_of_units || 1) * (previous.quantity || 1) * price * (1 - (previous.discount_percent || 0) / 100) })); };
  const handleFile = async (event: React.ChangeEvent<HTMLInputElement>) => { const file = event.target.files?.[0]; if (!file) return; setUploading(true); try { update('image_url', await onUpload(file)); } finally { setUploading(false); event.target.value = ''; } };
  const save = () => { if (!draft.name.trim() || draft.unit_price <= 0) return; onSave({ ...draft, amount, area_sqft: isModular ? parseFloat(((draft.width || 0) * (draft.height || 0)).toFixed(2)) : draft.area_sqft }); };
  return <div className="fixed inset-0 z-50 flex justify-end bg-black/40" role="dialog" aria-modal="true"><button type="button" className="absolute inset-0 cursor-default" onClick={onClose} aria-label="Close drawer" /><aside className="relative flex h-full w-full max-w-xl flex-col bg-white shadow-2xl"><div className="flex items-center justify-between border-b border-gray-200 px-5 py-4"><div><h2 className="text-xl font-semibold text-secondary-800">{item ? 'Edit Item' : 'Add Item'}</h2><p className="text-xs text-gray-500">{roomName}</p></div><button type="button" onClick={onClose} className="rounded-lg p-2 text-gray-500 hover:bg-gray-100" aria-label="Close"><X className="h-5 w-5" /></button></div><div className="flex-1 space-y-4 overflow-y-auto px-5 py-5">
    <div className="grid grid-cols-2 gap-3"><label className="text-sm font-medium text-gray-700">Item type<select value={draft.item_type} onChange={event => update('item_type', event.target.value as QuoteItem['item_type'])} className="mt-1 w-full rounded-lg border border-gray-300 px-3 py-2 font-normal"><option value="material">Material</option><option value="labor">Labor</option><option value="service">Service</option><option value="component">Component</option><option value="other">Other</option></select></label><label className="text-sm font-medium text-gray-700">Pricing mode<select value={isModular ? 'modular' : 'standard'} onChange={event => update('section', event.target.value === 'modular' ? 'modular' : roomName as QuoteItem['section'])} className="mt-1 w-full rounded-lg border border-gray-300 px-3 py-2 font-normal"><option value="standard">Quantity × rate</option><option value="modular">Dimensions × rate</option></select></label></div>
    {draft.item_type === 'material' && <label className="block text-sm font-medium text-gray-700">Material<select value={draft.material_id || ''} onChange={event => selectMaterial(event.target.value)} className="mt-1 w-full rounded-lg border border-gray-300 px-3 py-2 font-normal"><option value="">Select from catalog</option>{materials.map(material => <option key={material.id} value={material.id}>{material.name} · {formatCurrency(material.is_discounted && material.discount_price !== null ? material.discount_price : material.base_price)}/{material.unit}</option>)}</select></label>}
    <label className="block text-sm font-medium text-gray-700">Item name<input value={draft.name} onChange={event => update('name', event.target.value)} placeholder="e.g. TV Unit" className="mt-1 w-full rounded-lg border border-gray-300 px-3 py-2 font-normal" /></label>
    <label className="block text-sm font-medium text-gray-700">Description<textarea value={draft.description} onChange={event => update('description', event.target.value)} rows={2} className="mt-1 w-full rounded-lg border border-gray-300 px-3 py-2 font-normal" /></label>
    <div><p className="mb-2 text-sm font-medium text-gray-700">Item image</p><div className="flex items-center gap-3">{draft.image_url ? <img src={draft.image_url} alt="Item" className="h-16 w-16 rounded-lg border object-cover" /> : <div className="flex h-16 w-16 items-center justify-center rounded-lg bg-gray-100 text-gray-400"><ImageIcon className="h-5 w-5" /></div>}<label className="cursor-pointer rounded-lg border border-primary-300 px-3 py-2 text-xs font-semibold text-primary-700 hover:bg-primary-50">{uploading ? 'Processing…' : draft.image_url ? 'Change image' : 'Upload image'}<input type="file" accept="image/*" onChange={handleFile} className="hidden" /></label>{draft.image_url && <button type="button" onClick={() => update('image_url', null)} className="text-xs font-semibold text-red-600">Remove</button>}</div></div>
    {isModular ? <div className="grid grid-cols-3 gap-3">{(['width', 'height', 'depth'] as const).map(field => <label key={field} className="text-sm font-medium capitalize text-gray-700">{field}<input type="number" min="0" step="0.01" value={draft[field] ?? ''} onChange={event => update(field, event.target.value === '' ? undefined : parseFloat(event.target.value) || 0)} className="mt-1 w-full rounded-lg border border-gray-300 px-3 py-2 font-normal" /></label>)}</div> : <div className="grid grid-cols-3 gap-3"><label className="text-sm font-medium text-gray-700">Units<input type="number" min="1" step="1" value={draft.number_of_units} onChange={event => update('number_of_units', parseFloat(event.target.value) || 1)} className="mt-1 w-full rounded-lg border border-gray-300 px-3 py-2 font-normal" /></label><label className="text-sm font-medium text-gray-700">Quantity<input type="number" min="0" step="0.01" value={draft.quantity} onChange={event => update('quantity', parseFloat(event.target.value) || 0)} className="mt-1 w-full rounded-lg border border-gray-300 px-3 py-2 font-normal" /></label><label className="text-sm font-medium text-gray-700">Unit<input value={draft.unit} onChange={event => update('unit', event.target.value)} className="mt-1 w-full rounded-lg border border-gray-300 px-3 py-2 font-normal" /></label></div>}
    <div className="grid grid-cols-2 gap-3"><label className="text-sm font-medium text-gray-700">Unit price<input type="number" min="0" step="0.01" value={isModular ? (draft.per_sqft_rate ?? draft.unit_price) : draft.unit_price} onChange={event => { const value = parseFloat(event.target.value) || 0; update('unit_price', value); if (isModular) update('per_sqft_rate', value); }} className="mt-1 w-full rounded-lg border border-gray-300 px-3 py-2 font-normal" /></label><label className="text-sm font-medium text-gray-700">Discount %<input type="number" min="0" max="100" step="0.01" value={draft.discount_percent || ''} onChange={event => update('discount_percent', parseFloat(event.target.value) || 0)} className="mt-1 w-full rounded-lg border border-gray-300 px-3 py-2 font-normal" /></label></div>
    <div className="rounded-xl bg-primary-50 p-4"><p className="text-xs font-medium uppercase tracking-wide text-primary-700">Calculated amount</p><p className="mt-1 text-2xl font-bold text-primary-800">{formatCurrency(amount)}</p></div>
  </div><div className="flex gap-3 border-t border-gray-200 p-5"><button type="button" onClick={onClose} className="flex-1 rounded-xl border border-gray-300 px-4 py-3 font-semibold text-gray-700 hover:bg-gray-50">Cancel</button><button type="button" onClick={save} disabled={!draft.name.trim() || draft.unit_price <= 0 || uploading} className="flex-1 rounded-xl bg-primary-600 px-4 py-3 font-semibold text-white hover:bg-primary-700 disabled:cursor-not-allowed disabled:opacity-50">Save Item</button></div></aside></div>;
};
export default QuoteItemDrawer;
